{
  imports = [
    <home-manager/nixos>
    /etc/nixos/hardware-configuration.nix 
    /home/sa3urn/Dotfiles/configs/kitty.nix
    /home/sa3urn/Dotfiles/configs/window-manager/hyprland.nix
    /home/sa3urn/Dotfiles/configs/window-manager/waybar.nix
    /home/sa3urn/Dotfiles/configs/system/bash.nix
    /home/sa3urn/Dotfiles/configs/hardware/tlp.nix
    /home/sa3urn/Dotfiles/configs/hardware/pipewire.nix
    /home/sa3urn/Dotfiles/configs/hardware/bluetooth.nix
    /home/sa3urn/Dotfiles/configs/steam.nix
    /home/sa3urn/Dotfiles/configs/vscode.nix
    /home/sa3urn/Dotfiles/configs/system/autologin.nix
    /home/sa3urn/Dotfiles/configs/git.nix
    /home/sa3urn/Dotfiles/configs/system/polkit.nix
    /home/sa3urn/Dotfiles/configs/window-manager/gtk.nix
    /home/sa3urn/Dotfiles/configs/system/locales.nix
    /home/sa3urn/Dotfiles/configs/hardware/network.nix
    /home/sa3urn/Dotfiles/configs/pkgs.nix
    /home/sa3urn/Dotfiles/configs/system/home-manager.nix
    /home/sa3urn/Dotfiles/configs/system/nixos.nix
    /home/sa3urn/Dotfiles/configs/system/users.nix
    /home/sa3urn/Dotfiles/configs/hardware/bootloader.nix
  ];
}